
openapi: 3.0.0
info:
  title: Kletis Forum API - Posts
  description: API for managing posts in tractor categories
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local development server

paths:
  /posts/:
    get:
      summary: Get all posts
      responses:
        '200':
          description: List of all posts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
        '500':
          description: Server error

    post:
      summary: Create a new post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
      responses:
        '201':
          description: Post created successfully
        '400':
          description: Validation error

  /posts/{id}:
    get:
      summary: Get a post by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Post found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        '404':
          description: Post not found

    put:
      summary: Update a post by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
      responses:
        '200':
          description: Post updated successfully
        '404':
          description: Post not found
        '400':
          description: Validation error

    delete:
      summary: Delete a post by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Post deleted successfully
        '404':
          description: Post not found
        '500':
          description: Server error

components:
  schemas:
    Post:
      type: object
      properties:
        _id:
          type: string
          description: Unique identifier of the post
        title:
          type: string
          description: The title of the post
        content:
          type: string
          description: The content of the post
        author:
          type: string
          description: The ID of the user who created the post
        tractor:
          type: string
          description: The ID of the tractor (subreddit) this post belongs to
        upvotes:
          type: integer
          description: Number of upvotes on the post
        downvotes:
          type: integer
          description: Number of downvotes on the post
        created_at:
          type: string
          format: date-time
          description: Timestamp when the post was created
        updated_at:
          type: string
          format: date-time
          description: Timestamp of the last update
